#!/usr/bin/env python3
"""Write docs/USAGE.md by asking the program what it does.

Documentation that a model writes drifts from the code the moment the
code changes. Documentation derived by running `--help` cannot drift: it
is regenerated from the thing it describes. This is law, so no model is
consulted anywhere in this file.

Also rewrites the block between the README markers, so the front page
stays true without anyone maintaining it.

    python3 tools/docgen.py
"""

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN USAGE -->"
END = "<!-- END USAGE -->"


def run(args, timeout=20):
    try:
        p = subprocess.run([sys.executable] + args, cwd=str(ROOT),
                           capture_output=True, text=True, timeout=timeout)
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.SubprocessError as e:
        return 1, str(e)


def subcommand_names(help_text):
    """The {a,b,c} list argparse prints in its usage line."""
    for line in help_text.splitlines():
        if "{" in line and "}" in line:
            inner = line[line.index("{") + 1:line.index("}")]
            return [s.strip() for s in inner.split(",") if s.strip()]
    return []


def fence(text):
    return "```\n" + text.rstrip() + "\n```"


def cli_section():
    if not (ROOT / "cli.py").exists():
        return None, []
    rc, top = run(["cli.py", "--help"])
    if rc != 0:
        return "`cli.py --help` currently fails:\n\n" + fence(top), []
    names = subcommand_names(top)
    parts = ["### Overview", "", fence(top)]
    for n in names:
        rc, h = run(["cli.py", n, "--help"])
        parts += ["", "### `%s`" % n, "", fence(h if rc == 0 else "(--help failed)\n" + h)]
    return "\n".join(parts), names


def http_section():
    """Routes are read from source, not by starting a server."""
    api = ROOT / "api"
    if not api.is_dir():
        return None
    sys.path.insert(0, str(ROOT / "tools"))
    import survey  # same directory, deliberately reused rather than duplicated
    rows = survey.routes()
    if not rows:
        return None
    lines = ["| method | path | module |", "|---|---|---|"]
    for r in rows:
        lines.append("| %s | `%s` | `api/%s` |" % (r.get("method", "?"), r["path"], r["module"]))
    return "\n".join(lines)


def db_section():
    sys.path.insert(0, str(ROOT / "tools"))
    import survey
    rows = survey.tables()
    if not rows:
        return None
    lines = ["| table | columns | rows |", "|---|---|--:|"]
    for t in rows:
        lines.append("| `%s` | %s | %d |" % (
            t["table"], ", ".join("`%s`" % c for c in t["columns"]), t["rows"]))
    return "\n".join(lines)


def build():
    out = ["# Usage", "",
           "Generated by `python3 tools/docgen.py` from the program itself.",
           "Do not edit by hand; it is overwritten.", ""]
    cli, names = cli_section()
    if cli:
        out += ["## Command line", "", cli, ""]
    http = http_section()
    if http:
        out += ["## HTTP API", "", http, ""]
    db = db_section()
    if db:
        out += ["## Database", "", db, ""]
    if len(out) <= 5:
        out += ["Nothing is built yet.", ""]
    return "\n".join(out), names


def sync_readme(names):
    p = ROOT / "README.md"
    if not p.exists():
        return False
    text = p.read_text(encoding="utf-8", errors="replace")
    if BEGIN not in text or END not in text:
        return False
    if names:
        block = ("\n%s\n\n" % BEGIN) + "Subcommands: " + ", ".join(
            "`%s`" % n for n in names) + "\n\nSee [docs/USAGE.md](docs/USAGE.md).\n\n" + END + "\n"
    else:
        block = "\n%s\n\nSee [docs/USAGE.md](docs/USAGE.md).\n\n%s\n" % (BEGIN, END)
    head = text[:text.index(BEGIN)].rstrip("\n")
    tail = text[text.index(END) + len(END):].lstrip("\n")
    p.write_text(head + block + tail, encoding="utf-8")
    return True


def main():
    text, names = build()
    d = ROOT / "docs"
    d.mkdir(exist_ok=True)
    (d / "USAGE.md").write_text(text, encoding="utf-8")
    print("wrote docs/USAGE.md (%d bytes, %d subcommand(s))" % (len(text), len(names)))
    if sync_readme(names):
        print("synced README.md usage block")
    return 0


if __name__ == "__main__":
    sys.exit(main())
